apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  # similar to NodePort but only works on cloud platforms
  # using locally, would work the same as using NodePort
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
