apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      # If nodeport is not defined, one will be automatically assigned within the range
      nodePort: 30008
  selector:
    app: nginx
    type: front-end
