#replication set
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp-replicaset
  labels:
    app: myapp-replicaset
    type: front-end
spec:
  template: 
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
    spec:
      containers: 
        - name: nginx
          image: nginx
  # how many pods we'll create
  replicas: 3

  # major difference between replication controller and replicaset
  selector: 
    # what pods fall under it
    # pods created before the replicaset created that matched label, replica set will also consider those with the label
    # which pods to monitor -- there may be many other pods in the container with different labels
    matchLabels:
      type: front-end

  # to execute:
  # $ kubectl create -f .\replicaset.yml

  # to update an existing replicaset (say update the replicas from 3 to 6) WITH changing the file directly
  # kubectl replace -f .\replicaset.yml

  # to update an existing replicaset (say update the replicas from 3 to 6) WITHOUT updating the file directly (file will NOT be modified)
  # kubectl scale --replicas=6 -f .\replicaset.yml

  # for troubleshooting:
  # shows what is happening with the pods 
  # $ kubectl describe replicaset myapp-replicaset